name: anime_app_tv
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  auto_size_text: ^3.0.0
  bloc: ^8.1.2
  bot_toast: ^4.0.4
  # dart_ping: ^9.0.0
  # dart_ping_ios: ^4.0.1
  dartz: ^0.10.1
  dio: ^5.3.2
  equatable: ^2.0.5
  flutter_animate: ^4.2.0+1
  flutter_bloc: ^8.1.3
  flutter_modular: ^6.3.2
  flutter_svg: ^2.0.7
  flutter_vibrate: ^1.3.0
  gap: ^3.0.1
  loading_animation_widget: ^1.2.0+4
  scaffold_gradient_background: ^1.0.3+1
  shared_preferences: ^2.2.1
  flutter_native_splash: ^2.3.2
  flextras: ^1.0.0
  html: ^0.15.4
  media_kit: ^1.1.7                              # Primary package.
  media_kit_video: ^1.1.8                        # For video rendering.
  ulid: ^2.0.0
  media_kit_libs_video: ^1.0.1         
  internet_connection_checker_plus: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/svgs/
    - shorebird.yaml

  fonts:
    - family: RobotoSlab
      fonts:
        - asset: assets/fonts/RobotoSlab-Regular.ttf
          weight: 400
        - asset: assets/fonts/RobotoSlab-Bold.ttf
          weight: 700